### PR TITLE
fix/167: Add WooPayments compatibility

### LINKED ISSUE #167: Incompatible with WooPayments multi currency
### Describe the Bug

With Payfast and WooPayments (with multi-currency enabled) on the same site, Payfast doesn't show up as a payment method on the checkout page.

### To Reproduce

1. Install and activate WooPayments. Enable multi-currency and add a currency other than Rand
2. Payfast is not available at checkout :(

### Expected Behavior

For Payfast to still show up, at least if the order currency is Rand.

### Actual Behavior

Payfast doesn't show up.

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

### PR DESCRIPTION
**Pull request by Sidsector9**
### All Submissions:

* [ ] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

Closes #167 .

### Steps to test the changes in this Pull Request:

1. Set USD as the store currency.
2. Add `ZAR` to WooPayments multi-currency.
3. Ensure WooPayments and Payfast are both enabled.
4. Visit the shop page and set the currency to `ZAR`, add a product to cart and visit checkout page.
5. Observe Payfast gateway is not in the list.
6. Switch to fix branch and repeat (4).
7. Observe Payfast is in the list.

### Changelog entry

> Fix - Payfast gateway not visible on Checkout when `ZAR` currency is set via WooPayments multi-currency feature.

### CODE REVIEW

File: includes/class-wc-gateway-payfast.php [hunk 1]
```diff
@@ -1796,4 +1797,45 @@ public function display_order_net( $order_id ) {
...
+					wp_unslash( $_GET['currency'] ) // phpcs:ignore WordPress.Security.NonceVerification.Recommended
+				),
+			);
+			// Check if the currency is set in the session (for logged-out users).
+		} elseif ( 0 === $user_id && WC()->session ) {
+			$currency_code = WC()->session->get( \WCPay\MultiCurrency\MultiCurrency::CURRENCY_SESSION_KEY );
+			// Check if the currency is set in the user meta (for logged-in users).
+		} elseif ( $user_id ) {
+			$currency_code = get_user_meta( $user_id, \WCPay\MultiCurrency\MultiCurrency::CURRENCY_META_KEY );
+		}
```
Comment (dkotter) [inline includes/class-wc-gateway-payfast.php]: I'm not familiar with how multi-currency works so this feedback may not make sense. But wondering if there's a scenario where the user session or user meta hasn't been set and thus the currency code ends up being empty here?

I guess wondering if we should separate this code into two `if` statements. So we check for the currency value from the URL first and store that in the `$currency_code` variable. And then we overwrite that value from session or user meta, if that value exists in either. Something like:
```php
$currency_code = '';
if ( isset( $_GET['currency'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
	$currency_code = array(
		sanitize_text_field(
			wp_unslash( $_GET['currency'] ) // phpcs:ignore WordPress.Security.NonceVerification.Recommended
		),
	);
}

// Check if the currency is set in the session (for logged-out users).
if ( 0 === $user_id && WC()->session ) {
	$stored_code = WC()->session->get( \WCPay\MultiCurrency\MultiCurrency::CURRENCY_SESSION_KEY );

	// Not sure the best check on this value? Should it always be an array and we can check for that? Can it sometimes be a string?
	if ( $stored_code ) {
		$currency_code = $stored_code;
	}
// Check if the currency is set in the user meta (for logged-in users).
} elseif ( $user_id ) {
	$stored_code = get_user_meta( $user_id, \WCPay\MultiCurrency\MultiCurrency::CURRENCY_META_KEY );

	// Not sure the best check on this value? Should it always be an array and we can check for that? Can it sometimes be a string?
	if ( $stored_code ) {
		$currency_code = $stored_code;
	}
}
```

Comment (Sidsector9) [reply includes/class-wc-gateway-payfast.php]: @dkotter I've fixed the confusion between the return value types `array` vs `string`. There was a small bug, thanks for pointing that out.

Regarding separating if statements into 2, the problem is that in Block Checkout, the user meta is saved after the block is rendered. So the block checkout page requires an additional reload for Payfast to appear in the list of gateways. We give precedence to the GET parameter, if that is set, then we use it, because ultimately that gets saved to the session and user meta.

**Review by dkotter — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
**QA/Test Report-** ✅ 
------------

**Testing Environment -** 

<Details>

* WordPress: 6.4.3
* Theme: Storefront Version: 4.5.4
* WooCommerce - Version 8.6.1
* PHP: 8.0.22 
* Web Server: Nginx
* Browser: Chrome - Version 121
* OS: macOS Sonoma 14.3  
* Git Branch: fix/167


</Details>

**Test Results -** 

**Functional Demo /  Screencast -**

PayFast payment gateway is available on checkout when customers use 'Rand' as a currency from WooPayment currency selection option.
Cross tested scenario when Store also has 'Rand' as a store currency and WooPayment installed. 


https://github.com/woocommerce/woocommerce-gateway-payfast/assets/6384299/954d0dd7-15c5-48b9-84d9-72271d8f9b55


**Next Step-** Ready to UAT

**Testing Documentation Status-**

Cases related to this PR/Issue, are added to Critical Flow Wiki Pages: 

- [ ] Yes  
- [ ] Not Required/ Applicable for this PR

**Review by ankitguptaindia — APPROVED** [review]

**Comment by ankitguptaindia** [comment]
**Regression+Smoke Test Report-** ✅ 
------------

**Testing Environment -** 


<Details>

* WordPress: 6.5-RC1
* Theme: Storefront Version: 4.5.4
* WooCommerce - Version 8.7.0
* PHP: 8.3.0 
* Web Server: Nginx
* Browser: Chrome - Version 122
* OS: macOS Monterey 

</Details>

Tested with Archive File created via 

```php woorelease.phar build smoke-testing branch _URL_ ```

- Composer version - v2.3.5
- npm version - v8.19.2
- node version - v16.18.1

#### Please note that this plugin has been tested with the build created by the specified versions ☝🏼 of Composer, Node, and NPM. 



**Status-**  Working as expected. Ready to merge 🚀
